-- This file was automatically generated by AlyxLib.

-- alyxlib can only run on server
if IsServer() then
    -- Load alyxlib before using it, in case this mod loads before the alyxlib mod.
    require("alyxlib.init")

    -- execute code or load mod libraries here
    require "akimbo.classes.akimbo_weapon"
    require "akimbo.classes.akimbo_pistol"
    require "akimbo.classes.akimbo_rapidfire"
    require "akimbo.akimbo_controller"
    require "akimbo.weapon_override"
    require "akimbo.commands"
    require "akimbo.convars"
    require "akimbo.debug"
    require "akimbo.debug_menu"
end